Repository 4pet-social/4pet, pull requests merged in 2019-12, with the labels that each got.

#80 Complete post modal
  petisland_core/lib/domain/base_model.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/pet.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/domain/post_image.dart
  petisland_core/lib/domain/post_tag.dart
  petisland_core/test/domain_test/json_parser_test.dart
Labels: new feature

#81 Format code
  lib/authentication_bloc/authentication_bloc.dart
  lib/common/common.dart
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_shadows.dart
  lib/home_page/home_page.dart
  lib/home_page/widget/bottom_bar/bottom_bar.dart
  lib/home_page/widget/bottom_bar/bottom_bar_widget.dart
  lib/login/bloc/login_bloc.dart
  lib/login/widget/widget.dart
  lib/main.dart
  lib/main_app/main_app.dart
  lib/main_bloc/main_app_event.dart
  lib/main_bloc/t_bloc.dart
  lib/message/message.dart
  lib/notification/notification.dart
  lib/pet_feed/pet_feed.dart
  lib/petisland.dart
  lib/setting/setting.dart
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/config/firebase_config.dart
  petisland_core/lib/domain/base_model.dart
  petisland_core/lib/domain/login_data.dart
  petisland_core/lib/domain/user.dart
  petisland_core/lib/petisland_core.dart
  petisland_core/lib/repository/tag_repository.dart
  petisland_core/lib/service/image_service.dart
  petisland_core/lib/service/service.dart
  petisland_core/lib/util/log.dart
Labels: enhancement

#83 Complete worker upload
  lib/main_app/main_app_screen.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_bloc.dart
  lib/main_bloc/worker_upload.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/widget/chungloai_post_input.dart
  petisland_core/lib/exception/petisland_api_exception.dart
  petisland_core/lib/util/petisland_constants.dart
Labels: new feature

#85 Update post modal
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/panel.dart
  petisland_core/lib/domain/panel_detail.dart
  petisland_core/lib/domain/pet_category.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: new feature, service

#86 Complete render pet category
  lib/common/widgets/t_dropdown.dart
  lib/common/widgets/widgets.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/widget/chungloai_post_input.dart
  lib/post/post_edit/widget/pet_category_input.dart
  lib/post/post_edit/widget/post_edit_body.dart
  lib/post/post_edit/widget/widget.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: enhancement, new feature, render ui

#87 Update post service
  petisland_core/lib/domain/panel.dart
  petisland_core/lib/domain/panel_detail.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: new feature, service

#90 Complete render layout post
  lib/common/state/petisland_stateless_wiget.dart
  lib/common/state/state.dart
  lib/common/widgets/t_circle_button.dart
  lib/common/widgets/t_page_route.dart
  lib/common/widgets/widgets.dart
  lib/home_page/widget/widget.dart
  lib/pet_feed/pet_feed.dart
  lib/pet_feed/pet_feed_screen.dart
Labels: new feature, render ui

#93 Post edit screen
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Flutter/flutter_export_environment.sh
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  lib/common/resources/font_families.dart
  lib/common/resources/t_colors.dart
  lib/common/widgets/t_cached_image_widget.dart
  lib/common/widgets/t_dropdown.dart
  lib/common/widgets/t_sheet.dart
  lib/common/widgets/widgets.dart
  lib/login/widget/user_input_widget.dart
  lib/main_app/main_app_screen.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_bloc.dart
  lib/main_bloc/worker_upload.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/pet_feed/pet_feed.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/post/post_edit/bloc/bloc.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/bloc/post_edit_event.dart
  lib/post/post_edit/bloc/post_edit_state.dart
  lib/post/post_edit/post_edit.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/screen/screen.dart
  lib/post/post_edit/widget/add_image_post_widget.dart
  lib/post/post_edit/widget/desc_post_input.dart
  lib/post/post_edit/widget/expand_widget.dart
  lib/post/post_edit/widget/image_choose_popup.dart
  lib/post/post_edit/widget/image_post_input.dart
  lib/post/post_edit/widget/image_post_widget.dart
  lib/post/post_edit/widget/location_post_input.dart
  lib/post/post_edit/widget/pet_category_input.dart
  lib/post/post_edit/widget/post_edit_body.dart
  lib/post/post_edit/widget/price_post_input.dart
  lib/post/post_edit/widget/send_widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  lib/post/post_edit/widget/title_post_input.dart
  lib/post/post_edit/widget/widget.dart
  petisland_core/lib/config/config.dart
  petisland_core/lib/domain/post_modal.dart
  petisland_core/lib/exception/petisland_api_exception.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/service_test/post_service_test.dart
  pubspec.yaml
Labels: new feature

#94 Feed render engine
  lib/home_page/home_page_screen.dart
  lib/home_page/widget/bottom_bar/bottom_bar_widget.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/pet_feed/bloc/bloc.dart
  lib/pet_feed/bloc/pet_feed_bloc.dart
  lib/pet_feed/bloc/pet_feed_controller.dart
  lib/pet_feed/bloc/pet_feed_event.dart
  lib/pet_feed/bloc/pet_feed_state.dart
  lib/pet_feed/pet_feed.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/pet_feed/widget/panel_render.dart
  lib/pet_feed/widget/pet_category_widget.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post_item_render.dart
  lib/pet_feed/widget/post_widget.dart
  lib/pet_feed/widget/trending_panel_widget.dart
  lib/pet_feed/widget/widget.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/util/petisland_constants.dart
Labels: new feature, render ui

#96 Handle bug get category :bug:
  lib/authentication_bloc/authentication_bloc.dart
  lib/post/post_edit/widget/pet_category_input.dart
  lib/post/post_edit/widget/widget.dart
  petisland_core/lib/module/dev_module_core.dart
Labels: bug

#99 Handle remove some rule
  analysis_options.yaml
  lib/authentication_bloc/authentication_event.dart
  lib/authentication_bloc/authentication_state.dart
  lib/common/resources/font_families.dart
  lib/common/resources/t_asserts.dart
  lib/common/resources/t_constant.dart
  lib/common/resources/t_navigator_observer.dart
  lib/common/widgets/t_page_route.dart
  lib/home_page/widget/bottom_bar/bottom_bar_widget.dart
  lib/login/bloc/login_bloc.dart
  lib/login/bloc/login_event.dart
  lib/login/bloc/login_state.dart
  lib/login/widget/loading_widget.dart
  lib/login/widget/login_detail_widget.dart
  lib/main.dart
  lib/main_app/main_app_screen.dart
  lib/main_bloc/t_bloc.dart
  lib/main_bloc/worker_upload.dart
  lib/message/message_screen.dart
  lib/notification/notification_screen.dart
  lib/pet_feed/bloc/pet_feed_bloc.dart
  lib/pet_feed/bloc/pet_feed_event.dart
  lib/pet_feed/bloc/pet_feed_state.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/bloc/post_edit_event.dart
  lib/post/post_edit/bloc/post_edit_state.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/widget/desc_post_input.dart
  lib/post/post_edit/widget/image_choose_popup.dart
  lib/post/post_edit/widget/location_post_input.dart
  lib/post/post_edit/widget/post_edit_body.dart
  lib/post/post_edit/widget/price_post_input.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  lib/post/post_edit/widget/title_post_input.dart
  lib/setting/setting_screen.dart
  petisland_core/lib/domain/post_image.dart
  petisland_core/lib/domain/post_modal.dart
  petisland_core/lib/domain/post_tag.dart
  petisland_core/lib/exception/petisland_api_exception.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/repository/image_repository.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/repository/tag_repository.dart
  petisland_core/lib/util/log.dart
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/enum_test.dart
  petisland_core/test/service_test/pet_category_service_test.dart
  petisland_core/test/service_test/post_service_test.dart
  petisland_core/test/service_test/tag_service_test.dart
  test_driver/app_test.dart
Labels: enhancement

#100 Complete render post preview :tada: :tada: :tada:
  analysis_options.yaml
  assets/flare/like.flr
  assets/icons/cat.svg
  assets/icons/kitty.svg
  assets/icons/user.svg
  lib/common/resources/resources.dart
  lib/common/resources/t_asserts.dart
  lib/common/resources/t_assets.dart
  lib/common/widgets/t_cached_image_widget.dart
  lib/login/widget/loading_widget.dart
  lib/main.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  lib/main_bloc/t_worker_state.dart
  lib/module/dev_module.dart
  lib/pet_feed/bloc/pet_feed_controller.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post/post_button_bar_widget.dart
  lib/pet_feed/widget/post/post_button_like_widget.dart
  lib/pet_feed/widget/post/post_button_widget.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_location_widget.dart
  lib/pet_feed/widget/post/post_money_widget.dart
  lib/pet_feed/widget/post/post_time_widget.dart
  lib/pet_feed/widget/post/post_title_widget.dart
  lib/pet_feed/widget/post/post_user_info_widget.dart
  lib/pet_feed/widget/post/post_widget.dart
  lib/pet_feed/widget/post_widget.dart
  lib/pet_feed/widget/trending_panel_widget.dart
  lib/pet_feed/widget/widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  petisland_core/lib/domain/account.dart
  petisland_core/lib/domain/base_model.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/module/module.dart
  petisland_core/lib/util/time.dart
  petisland_core/pubspec.yaml
  pubspec.yaml
Labels: new feature, render ui

#102 Complete handle likes
  lib/pet_feed/widget/post/post_button_like_widget.dart
  petisland_core/lib/domain/post.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: enhancement, render ui

#104 Complete change color log
  petisland_core/lib/util/log.dart
  petisland_core/pubspec.yaml
  pubspec.yaml
Labels: enhancement

#106 Fix error when navigate to edit post
  lib/common/resources/t_assets.dart
  lib/common/resources/t_colors.dart
  lib/common/widgets/t_dropdown.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_location_widget.dart
  lib/pet_feed/widget/post/post_money_widget.dart
  lib/pet_feed/widget/post/post_time_widget.dart
  lib/pet_feed/widget/post/post_title_widget.dart
  lib/pet_feed/widget/post/post_widget.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/bloc/post_edit_event.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/widget/add_image_post_widget.dart
  lib/post/post_edit/widget/desc_post_input.dart
  lib/post/post_edit/widget/image_post_input.dart
  lib/post/post_edit/widget/location_post_input.dart
  lib/post/post_edit/widget/pet_category_input.dart
  lib/post/post_edit/widget/post_edit_body.dart
  lib/post/post_edit/widget/price_post_input.dart
  lib/post/post_edit/widget/send_widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  lib/post/post_edit/widget/title_post_input.dart
  lib/post/post_edit/widget/widget.dart
  petisland_core/lib/util/log.dart
  petisland_core/lib/util/time.dart
Labels: enhancement, render ui

#109 Complete handle error get pet category
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/repository/pet_category_repository.dart
Labels: enhancement, service

#111 Add check code
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/service/account_service.dart
  petisland_core/test/service_test/account_service_test.dart
Labels: enhancement, service

#113 Update API register :hammer:
  petisland_core/lib/domain/user.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/service/account_service.dart
  petisland_core/test/service_test/account_service_test.dart
Labels: enhancement, service

#115 Complete UI Trending, popular
  lib/common/resources/t_colors.dart
  lib/common/resources/t_shadows.dart
  lib/pet_feed/widget/panel_render.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post/post_button_like_widget.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_widget.dart
  lib/pet_feed/widget/trending_panel/post_description_widget.dart
  lib/pet_feed/widget/trending_panel/post_trending_widget.dart
  lib/pet_feed/widget/trending_panel/trending_description_bar_widget.dart
  lib/pet_feed/widget/trending_panel/trending_panel.dart
  lib/pet_feed/widget/trending_panel/trending_panel_widget.dart
  lib/pet_feed/widget/trending_panel_widget.dart
  lib/pet_feed/widget/widget.dart
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/domain/panel_detail.dart
  petisland_core/lib/util/log.dart
  petisland_core/lib/util/petisland_constants.dart
Labels: enhancement, render ui

#116 Render listing pet category
  assets/icons/pet_type/bird.svg
  assets/icons/pet_type/cat.svg
  assets/icons/pet_type/dog.svg
  assets/icons/pet_type/fish.svg
  assets/icons/pet_type/other.svg
  lib/common/resources/resources.dart
  lib/common/resources/t_assets.dart
  lib/common/resources/t_gradients.dart
  lib/common/state/state.dart
  lib/common/widgets/widgets.dart
  lib/main_bloc/main_bloc.dart
  lib/pet_feed/widget/panel_render.dart
  lib/pet_feed/widget/pet_category_widget.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post_category/category_description_widget.dart
  lib/pet_feed/widget/post_category/category_image_widget.dart
  lib/pet_feed/widget/post_category/post_category.dart
  lib/pet_feed/widget/post_category/post_category_widget.dart
  lib/pet_feed/widget/post_panel/panel_description_bar_widget.dart
  lib/pet_feed/widget/post_panel/post_panel.dart
  lib/pet_feed/widget/post_panel/post_panel_description_widget.dart
  lib/pet_feed/widget/post_panel/post_panel_detail_widget.dart
  lib/pet_feed/widget/post_panel/post_panel_widget.dart
  lib/pet_feed/widget/widget.dart
  petisland_core/lib/client/client.dart
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/config/config.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/image.dart
  petisland_core/lib/domain/panel_detail.dart
  petisland_core/lib/domain/pet_category.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/module/module.dart
  petisland_core/lib/petisland_core.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/utils/log.dart
  petisland_core/lib/utils/petisland_constants.dart
  petisland_core/lib/utils/string.dart
  petisland_core/lib/utils/time.dart
  petisland_core/lib/utils/utils.dart
  petisland_core/pubspec.yaml
  petisland_core/test/domain_test/json_parser_test.dart
  petisland_core/test/enum_test.dart
  petisland_core/test/service_test/account_service_test.dart
  pubspec.yaml
Labels: enhancement, new feature, render ui

#118 Complete format code
  lib/authentication_bloc/authentication_bloc.dart
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/widgets/t_cached_image_widget.dart
  lib/common/widgets/t_page_route.dart
  lib/common/widgets/widgets.dart
  lib/home_page/widget/bottom_bar/bottom_bar.dart
  lib/login/widget/loading_widget.dart
  lib/login/widget/login_detail_widget.dart
  lib/login/widget/petisland_button_widget.dart
  lib/login/widget/user_input_widget.dart
  lib/login/widget/widget.dart
  lib/main.dart
  lib/main_app/main_app_screen.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_bloc.dart
  lib/pet_feed/bloc/bloc.dart
  lib/pet_feed/pet_feed.dart
  lib/pet_feed/widget/post/post_button_bar_widget.dart
  lib/pet_feed/widget/post/post_button_like_widget.dart
  lib/pet_feed/widget/post/post_button_widget.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_location_widget.dart
  lib/pet_feed/widget/post/post_money_widget.dart
  lib/pet_feed/widget/post/post_time_widget.dart
  lib/pet_feed/widget/post/post_title_widget.dart
  lib/pet_feed/widget/post/post_user_info_widget.dart
  lib/pet_feed/widget/post_category/post_category.dart
  lib/pet_feed/widget/post_panel/post_panel.dart
  lib/pet_feed/widget/widget.dart
  lib/post/post_edit/bloc/bloc.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/bloc/post_edit_state.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/widget/add_image_post_widget.dart
  lib/post/post_edit/widget/desc_post_input.dart
  lib/post/post_edit/widget/image_post_input.dart
  lib/post/post_edit/widget/image_post_widget.dart
  lib/post/post_edit/widget/location_post_input.dart
  lib/post/post_edit/widget/pet_category_input.dart
  lib/post/post_edit/widget/price_post_input.dart
  lib/post/post_edit/widget/title_post_input.dart
  lib/post/post_edit/widget/widget.dart
  lib/splash/splash_screen.dart
Labels: enhancement

#127 Update UI in post edit screen
  lib/login/widget/user_input_widget.dart
  lib/pet_feed/widget/post_category/category_description_widget.dart
  lib/post/post_edit/widget/desc_post_input.dart
  lib/post/post_edit/widget/image_post_widget.dart
  petisland_core/lib/utils/utils.dart
Labels: enhancement

#126 Register screen
  lib/login/widget/login_detail_widget.dart
  lib/login/widget/widget.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/register/bloc/bloc.dart
  lib/register/bloc/register_bloc.dart
  lib/register/bloc/register_event.dart
  lib/register/bloc/register_state.dart
  lib/register/register.dart
  lib/register/screen/register_email_screen.dart
  lib/register/screen/screen.dart
  lib/register/widget/register_email_widget.dart
  lib/register/widget/widget.dart
Labels: new feature, render ui

#129 Update message register step 1
  lib/login/widget/login_detail_widget.dart
  lib/register/bloc/register_bloc.dart
  lib/register/screen/register_email_screen.dart
  lib/register/screen/screen.dart
  lib/register/widget/register_email_widget.dart
Labels: enhancement, new feature, render ui

#131 Handle check token
  lib/authentication_bloc/authentication_bloc.dart
  lib/authentication_bloc/authentication_event.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post_panel/post_panel_widget.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/service/account_service.dart
Labels: enhancement

#136 Complete post detail
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post/post_button_bar.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_preview_widget.dart
  lib/pet_feed/widget/post/post_widget.dart
  lib/pet_feed/widget/post_panel/post_panel.dart
  lib/pet_feed/widget/post_panel/post_panel_widget.dart
  lib/pet_feed/widget/widget.dart
  lib/post/post.dart
  lib/post/post_detail/post_detail.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/screen/screen.dart
  lib/post/post_detail/widget/image_slider_widget.dart
  lib/post/post_detail/widget/post_description_widget.dart
  lib/post/post_detail/widget/post_detail_app_bar.dart
  lib/post/post_detail/widget/widget.dart
Labels: new feature, render ui

#138 Complete report post
  .prettierrc.yaml
  lib/common/resources/t_colors.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/widget/post_detail_app_bar.dart
  lib/post/post_detail/widget/report_option.dart
  lib/post/post_detail/widget/report_post_widget.dart
  lib/post/post_detail/widget/widget.dart
  lib/post/post_edit/widget/image_post_input.dart
  petisland_core/lib/utils/petisland_constants.dart
Labels: enhancement, new feature, render ui

#140 Complete report service
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/report.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/report_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/report_service.dart
  petisland_core/lib/service/service.dart
Labels: new feature, service

#142 Complete report
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/widget/report_post_widget.dart
  petisland_core/lib/repository/report_repository.dart
  petisland_core/lib/utils/petisland_constants.dart
Labels: new feature, render ui, service

#143 Complete refresh post
  lib/authentication_bloc/authentication_bloc.dart
  lib/pet_feed/bloc/pet_feed_controller.dart
  lib/post/post_detail/screen/post_detail_screen.dart
Labels: enhancement

#145 Update size icon
  lib/common/resources/t_shadows.dart
  lib/common/widgets/t_circle_button.dart
Labels: enhancement

#147 Fix parse user from json :hammer:
  petisland_core/lib/domain/account.dart
Labels: enhancement

#149 Complete delete post service
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
Labels: enhancement, service

#151 Complete delete post
  lib/common/widgets/t_circle_button.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_worker.dart
  lib/pet_feed/bloc/pet_feed_controller.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post/post_widget.dart
  lib/pet_feed/widget/post_panel/post_panel.dart
  lib/pet_feed/widget/post_panel/post_panel_widget.dart
  lib/post/post_detail/screen/post_detail_screen.dart
Labels: enhancement

#153 Complete edit post
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/screen/screen.dart
  lib/post/post_detail/widget/image_slider_widget.dart
  lib/post/post_detail/widget/widget.dart
  lib/post/post_edit/bloc/bloc.dart
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/bloc/post_edit_event.dart
  lib/post/post_edit/bloc/post_edit_state.dart
  lib/post/post_edit/screen/post_edit_screen.dart
  lib/post/post_edit/widget/image_post_input.dart
  lib/post/post_edit/widget/image_post_widget.dart
  lib/post/post_edit/widget/post_edit_body.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/domain/post_create_modal.dart
  petisland_core/lib/domain/post_edit_modal.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/lib/utils/string.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: enhancement

#154 Add PetIsland badges
  README.md
Labels: new feature

#156 Complete update report
  lib/authentication_bloc/authentication_bloc.dart
  lib/post/post_detail/widget/report_post_widget.dart
  petisland_core/lib/repository/report_repository.dart
  petisland_core/lib/service/report_service.dart
Labels: enhancement, render ui

#157 Complete comment service
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/domain/comment.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/test/domain_test/json_parser_test.dart
Labels: enhancement, service

#159 Complete comment ui
  lib/common/common.dart
  lib/common/resources/resources.dart
  lib/common/resources/t_navigator_observer.dart
  lib/common/utils/account_utils.dart
  lib/common/utils/utils.dart
  lib/common/widgets/t_page_route.dart
  lib/common/widgets/widgets.dart
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/post/post_detail/bloc/bloc.dart
  lib/post/post_detail/bloc/comment_bloc.dart
  lib/post/post_detail/bloc/comment_event.dart
  lib/post/post_detail/bloc/comment_state.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/screen/screen.dart
  lib/post/post_detail/widget/comment/comment_default_widget.dart
  lib/post/post_detail/widget/comment/comment_description_widget.dart
  lib/post/post_detail/widget/comment/comment_input_bar_widget.dart
  lib/post/post_detail/widget/comment/comment_input_widget.dart
  lib/post/post_detail/widget/comment/comment_listing_widget.dart
  lib/post/post_detail/widget/comment/comment_widget.dart
  lib/post/post_detail/widget/post/image_slider_widget.dart
  lib/post/post_detail/widget/post/post_description_widget.dart
  lib/post/post_detail/widget/post/post_detail_app_bar.dart
  lib/post/post_detail/widget/post/post_detail_summary_widget.dart
  lib/post/post_detail/widget/report/report_option.dart
  lib/post/post_detail/widget/report/report_post_widget.dart
  lib/post/post_detail/widget/widget.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/lib/utils/time.dart
  petisland_core/lib/utils/utils.dart
  petisland_core/pubspec.yaml
Labels: enhancement, new feature, render ui

#160 Complete Chat
  analysis_options.yaml
  ios/Runner/Info.plist
  lib/chat/bloc/bloc.dart
  lib/chat/bloc/chat_bloc.dart
  lib/chat/bloc/chat_event.dart
  lib/chat/bloc/chat_state.dart
  lib/chat/chat.dart
  lib/chat/chat_screen.dart
  lib/home_page/home_page.dart
  lib/home_page/home_page_screen.dart
  lib/home_page/widget/bloc/bloc.dart
  lib/home_page/widget/bloc/navigation_bar_bloc.dart
  lib/home_page/widget/bloc/navigation_bar_event.dart
  lib/home_page/widget/bloc/navigation_bar_state.dart
  lib/home_page/widget/bottom_bar/bottom_bar.dart
  lib/home_page/widget/bottom_bar/bottom_bar_controller.dart
  lib/home_page/widget/bottom_bar/bottom_bar_widget.dart
  lib/message/message.dart
  lib/message/message_screen.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/pet_feed/widget/post/post.dart
  lib/pet_feed/widget/post/post_button_bar.dart
  pubspec.yaml
Labels: enhancement, render ui, service

#162 Complete profile ui
  assets/icons/logout.svg
  assets/icons/moon.svg
  assets/icons/note.svg
  lib/common/resources/t_assets.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_gradients.dart
  lib/home_page/home_page.dart
  lib/home_page/home_page_screen.dart
  lib/main.dart
  lib/profile/profile.dart
  lib/profile/profile_screen.dart
  lib/profile/widget/avatar_widget.dart
  lib/profile/widget/basic_function_widget.dart
  lib/profile/widget/profile_detail_widget.dart
  lib/profile/widget/setting_option_widget.dart
  lib/profile/widget/svg_icon_widget.dart
  lib/profile/widget/widget.dart
  lib/setting/setting.dart
  lib/setting/setting_screen.dart
  petisland_core/lib/domain/account.dart
Labels: new feature, render ui

#164 Complete dock appbar
  lib/common/resources/t_colors.dart
  lib/pet_feed/pet_feed_screen.dart
Labels: enhancement

#167 Complete define notification
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/notification.dart
Labels: enhancement, service

#169 Complete repository for notification
  petisland_core/lib/repository/notification_repository.dart
  petisland_core/lib/repository/repository.dart
Labels: enhancement, service

#170 Complete notification service
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/notification_repository.dart
  petisland_core/lib/service/notification_service.dart
  petisland_core/lib/service/service.dart
Labels: new feature, service

#172 Complete Feature notification UI
  lib/authentication_bloc/authentication_bloc.dart
  lib/common/common.dart
  lib/common/resources/t_colors.dart
  lib/common/widgets/avatar_widget.dart
  lib/common/widgets/svg_icon_widget.dart
  lib/common/widgets/widgets.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/notification/bloc/bloc.dart
  lib/notification/bloc/notification_bloc.dart
  lib/notification/bloc/notification_event.dart
  lib/notification/bloc/notification_state.dart
  lib/notification/notification.dart
  lib/notification/notification_screen.dart
  lib/notification/widget/notification_default_widget.dart
  lib/notification/widget/notification_message_widget.dart
  lib/notification/widget/notification_widget.dart
  lib/notification/widget/widget.dart
  lib/post/post_detail/widget/comment/comment_description_widget.dart
  lib/post/post_edit/widget/add_image_post_widget.dart
  lib/profile/profile.dart
  lib/profile/profile_screen.dart
  lib/profile/widget/choose_avatar_widget.dart
  lib/profile/widget/profile_detail_widget.dart
  lib/profile/widget/widget.dart
  petisland_core/lib/domain/notification.dart
  petisland_core/lib/repository/notification_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/notification_service.dart
  petisland_core/lib/utils/string.dart
  petisland_core/lib/utils/thin_id.dart
  petisland_core/lib/utils/utils.dart
Labels: enhancement

#174 Add get my post and post liked
  petisland_core/lib/repository/post_repository.dart
Labels: enhancement, service

#176 Complete service for update post
  petisland_core/lib/service/post_service.dart
Labels: enhancement

#179 Render my posts
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/profile/bloc/bloc.dart
  lib/profile/bloc/my_post/my_post.dart
  lib/profile/bloc/my_post/my_post_bloc.dart
  lib/profile/bloc/my_post/my_post_event.dart
  lib/profile/bloc/my_post/my_post_state.dart
  lib/profile/profile.dart
  lib/profile/screen/my_post_screen.dart
  lib/profile/screen/profile_screen.dart
  lib/profile/screen/screen.dart
  lib/profile/widget/basic_function_widget.dart
  lib/profile/widget/my_post/listing_post_widget.dart
  lib/profile/widget/my_post/my_post.dart
  lib/profile/widget/profile_detail_widget.dart
  lib/profile/widget/widget.dart
  petisland_core/lib/repository/post_repository.dart
Labels: enhancement, render ui

#182 Complete update register
  lib/common/state/petisland_stateless_wiget.dart
  lib/common/state/state.dart
  lib/register/bloc/register_bloc.dart
  lib/register/bloc/register_event.dart
  lib/register/bloc/register_state.dart
  lib/register/register.dart
  lib/register/screen/register_account_screen.dart
  lib/register/screen/register_code_screen.dart
  lib/register/screen/register_email_screen.dart
  lib/register/screen/screen.dart
  lib/register/widget/register_account_widget.dart
  lib/register/widget/register_code_widget.dart
  lib/register/widget/register_email_widget.dart
  lib/register/widget/widget.dart
Labels: new feature, render ui

#184 Update loading
  lib/login/widget/loading_widget.dart
Labels: new feature, render ui

#186 Complete rename app
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
Labels: enhancement

#191 Complete missing name
  lib/pet_feed/widget/post/post_preview_widget.dart
  lib/pet_feed/widget/post/post_user_info_widget.dart
  lib/post/post_detail/widget/comment/comment_description_widget.dart
Labels: new feature, render ui

#193 Complete icon logo person
  assets/icons/cat.svg
  assets/icons/kitty/kitty_1.svg
  assets/icons/kitty/kitty_10.svg
  assets/icons/kitty/kitty_11.svg
  assets/icons/kitty/kitty_12.svg
  assets/icons/kitty/kitty_13.svg
  assets/icons/kitty/kitty_14.svg
  assets/icons/kitty/kitty_15.svg
  assets/icons/kitty/kitty_16.svg
  assets/icons/kitty/kitty_17.svg
  assets/icons/kitty/kitty_18.svg
  assets/icons/kitty/kitty_19.svg
  assets/icons/kitty/kitty_2.svg
  assets/icons/kitty/kitty_20.svg
  assets/icons/kitty/kitty_21.svg
  assets/icons/kitty/kitty_22.svg
  assets/icons/kitty/kitty_23.svg
  assets/icons/kitty/kitty_24.svg
  assets/icons/kitty/kitty_25.svg
  assets/icons/kitty/kitty_26.svg
  assets/icons/kitty/kitty_27.svg
  assets/icons/kitty/kitty_28.svg
  assets/icons/kitty/kitty_29.svg
  assets/icons/kitty/kitty_3.svg
  assets/icons/kitty/kitty_30.svg
  assets/icons/kitty/kitty_31.svg
  assets/icons/kitty/kitty_32.svg
  assets/icons/kitty/kitty_33.svg
  assets/icons/kitty/kitty_34.svg
  assets/icons/kitty/kitty_35.svg
  assets/icons/kitty/kitty_36.svg
  assets/icons/kitty/kitty_37.svg
  assets/icons/kitty/kitty_38.svg
  assets/icons/kitty/kitty_39.svg
  assets/icons/kitty/kitty_4.svg
  assets/icons/kitty/kitty_40.svg
  assets/icons/kitty/kitty_41.svg
  assets/icons/kitty/kitty_42.svg
  assets/icons/kitty/kitty_43.svg
  assets/icons/kitty/kitty_44.svg
  assets/icons/kitty/kitty_45.svg
  assets/icons/kitty/kitty_46.svg
  assets/icons/kitty/kitty_47.svg
  assets/icons/kitty/kitty_48.svg
  assets/icons/kitty/kitty_49.svg
  assets/icons/kitty/kitty_5.svg
  assets/icons/kitty/kitty_50.svg
  assets/icons/kitty/kitty_6.svg
  assets/icons/kitty/kitty_7.svg
  assets/icons/kitty/kitty_8.svg
  assets/icons/kitty/kitty_9.svg
  lib/common/resources/resources.dart
  lib/common/resources/t_assets.dart
  lib/login/widget/widget.dart
  pubspec.yaml
Labels: enhancement

#195 Update post service get post by id
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
Labels: enhancement

#197 Complete navigate to post detail
  lib/notification/bloc/notification_bloc.dart
  lib/notification/notification.dart
  lib/notification/notification_screen.dart
  lib/notification/post_loading_screen.dart
  lib/post/post_detail/bloc/comment_bloc.dart
Labels: enhancement, render ui

#200 Fix missing image get image
  lib/post/post_edit/bloc/post_edit_bloc.dart
  lib/post/post_edit/widget/image_choose_popup.dart
  lib/post/post_edit/widget/image_post_input.dart
  lib/post/post_edit/widget/image_post_widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  pubspec.yaml
Labels: enhancement, service

#202 Update route api get list
  petisland_core/lib/repository/post_repository.dart
Labels: enhancement

#203 Update splash screen
  assets/images/app_icon.png
  assets/images/meow.jpeg
  flutter_native_splash.yaml
  lib/common/resources/t_assets.dart
  lib/splash/splash_screen.dart
  pubspec.yaml
  script/rebuild_splash_screen.sh
Labels: enhancement

#207 Fix random image when typing text
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
Labels: enhancement

#208 Complete delete comment
  lib/post/post_detail/bloc/comment_bloc.dart
  lib/post/post_detail/bloc/comment_event.dart
  lib/post/post_detail/widget/comment/comment_listing_widget.dart
Labels: enhancement, new feature

#209 Update fix upload post
  lib/main_bloc/t_worker.dart
Labels: bug, enhancement

#210 Complete notification
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  lib/main_bloc/t_worker_state.dart
  lib/module/dev_module.dart
  lib/pet_feed/bloc/bloc.dart
  lib/pet_feed/bloc/pet_feed_controller.dart
  lib/pet_feed/bloc/pet_feed_event.dart
  lib/pet_feed/bloc/pet_feed_state.dart
  lib/pet_feed/widget/pet_feed_detail_widget.dart
  petisland_core/lib/domain/panel_detail.dart
Labels: new feature

#211 Fix pagination for notification
  lib/notification/bloc/notification_bloc.dart
Labels: Deadline, bug
