Repository 4pet-social/4pet, pull requests merged in 2019-11, with the labels that each got.

#10 Complete setting http client
  lib/module/dev_module.dart
  petisland_core/lib/client/client.dart
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/config/config.dart
  petisland_core/lib/exeption/exception.dart
  petisland_core/lib/exeption/pesisland_exeption.dart
  petisland_core/lib/exeption/petisland_api_exception.dart
Labels: enhancement

#15 Complete format code
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/config/firebase_config.dart
  petisland_core/lib/domain/base_model.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/login_data.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/domain/user.dart
  petisland_core/lib/exception/petisland_api_exception.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/module/module.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/repository/user_repository.dart
  petisland_core/lib/service/account_service.dart
  petisland_core/lib/service/service.dart
  petisland_core/test/service_test/account_test.dart
Labels: enhancement

#23 Complete update export file
  lib/common/common.dart
  lib/common/export.dart
  lib/common/resources/export.dart
  lib/common/resources/font_families.dart
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_text_styles.dart
  lib/common/state/petisland_stateful_widget.dart
  lib/common/state/petisland_stateless_wiget.dart
  lib/common/state/state.dart
  lib/common/theme/theme.dart
  lib/main.dart
  lib/main_bloc/bloc_delegate.dart
  lib/main_bloc/export.dart
  lib/main_bloc/main_app_bloc.dart
  lib/main_bloc/main_bloc.dart
  lib/module/dev_module.dart
  lib/module/export.dart
  lib/module/module.dart
  lib/module/production_module.dart
  lib/petisland.dart
  lib/state/export.dart
Labels: new feature

#24 Complete update fonts
  assets/fonts/harmonia/HarmoniaSansProCyr-Black.ttf
  assets/fonts/harmonia/HarmoniaSansProCyr-Bold.ttf
  assets/fonts/harmonia/HarmoniaSansProCyr-Italic.ttf
  assets/fonts/harmonia/HarmoniaSansProCyr-Regular.ttf
  assets/fonts/harmonia/HarmoniaSansProCyr-SemiBd.ttf
  assets/fonts/sarabun/OFL.txt
  assets/fonts/sarabun/Sarabun-Bold.ttf
  assets/fonts/sarabun/Sarabun-BoldItalic.ttf
  assets/fonts/sarabun/Sarabun-ExtraBold.ttf
  assets/fonts/sarabun/Sarabun-ExtraBoldItalic.ttf
  assets/fonts/sarabun/Sarabun-ExtraLight.ttf
  assets/fonts/sarabun/Sarabun-ExtraLightItalic.ttf
  assets/fonts/sarabun/Sarabun-Italic.ttf
  assets/fonts/sarabun/Sarabun-Light.ttf
  assets/fonts/sarabun/Sarabun-LightItalic.ttf
  assets/fonts/sarabun/Sarabun-Medium.ttf
  assets/fonts/sarabun/Sarabun-MediumItalic.ttf
  assets/fonts/sarabun/Sarabun-Regular.ttf
  assets/fonts/sarabun/Sarabun-SemiBold.ttf
  assets/fonts/sarabun/Sarabun-SemiBoldItalic.ttf
  assets/fonts/sarabun/Sarabun-Thin.ttf
  assets/fonts/sarabun/Sarabun-ThinItalic.ttf
  lib/common/resources/font_families.dart
  lib/common/resources/t_text_styles.dart
  pubspec.yaml
Labels: new feature

#26 Complate upgrade version BLoC to v2.0
  lib/main.dart
  lib/main_bloc/main_app_bloc.dart
  pubspec.yaml
Labels: enhancement

#27 Complete setup theme
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_navigator_observer.dart
  lib/common/state/petisland_stateless_wiget.dart
  lib/common/theme/dark_theme.dart
  lib/common/theme/light_theme.dart
  lib/common/theme/theme.dart
  lib/main.dart
  lib/main_app/main_app.dart
  lib/main_app/main_app_screen.dart
  lib/main_bloc/bloc_delegate.dart
  lib/main_bloc/main_app_bloc.dart
  lib/main_bloc/main_app_event.dart
  lib/main_bloc/main_app_state.dart
  lib/main_bloc/main_bloc.dart
  lib/petisland.dart
  lib/splash/splash_screen.dart
  petisland_core/lib/module/prod_module_core.dart
  petisland_core/lib/util/log.dart
Labels: new feature

#28 Complete setup global auth
  lib/authentication_bloc/authentication_bloc.dart
  lib/authentication_bloc/authentication_event.dart
  lib/authentication_bloc/authentication_state.dart
  lib/login/login.dart
  lib/login/login_screen.dart
  lib/main.dart
  lib/main_app/main_app_screen.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  lib/petisland.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/service/account_service.dart
Labels: enhancement

#29 Login screen
  lib/authentication_bloc/authentication_bloc.dart
  lib/authentication_bloc/authentication_event.dart
  lib/authentication_bloc/authentication_state.dart
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_constant.dart
  lib/common/state/petisland_stateful_widget.dart
  lib/common/state/petisland_stateless_wiget.dart
  lib/home_page/home_page.dart
  lib/home_page/home_page_screen.dart
  lib/login/bloc/bloc.dart
  lib/login/bloc/login_bloc.dart
  lib/login/bloc/login_event.dart
  lib/login/bloc/login_state.dart
  lib/login/login.dart
  lib/login/login_screen.dart
  lib/login/widget/loading_widget.dart
  lib/login/widget/login_detail_widget.dart
  lib/login/widget/petisland_button_widget.dart
  lib/login/widget/user_input_widget.dart
  lib/login/widget/widget.dart
  lib/main.dart
  lib/main_app/main_app.dart
  lib/main_app/main_app_screen.dart
  lib/main_bloc/main_app_bloc.dart
  lib/main_bloc/main_app_event.dart
  lib/main_bloc/main_app_state.dart
  lib/main_bloc/main_bloc.dart
  lib/main_bloc/t_bloc.dart
  lib/module/dev_module.dart
  lib/module/module.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/account_service.dart
Labels: new feature

#31 Upgrade project support android x
  android/app/build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#33 Complete navigate bar
  assets/flare/loading.flr
  lib/home_page/home_page.dart
  lib/home_page/home_page_screen.dart
  lib/home_page/widget/bottom_bar/bottom_bar.dart
  lib/home_page/widget/bottom_bar/bottom_bar_item_widget.dart
  lib/home_page/widget/bottom_bar/bottom_bar_selector.dart
  lib/home_page/widget/bottom_bar/bottom_bar_widget.dart
  lib/home_page/widget/widget.dart
  lib/login/widget/loading_widget.dart
  lib/login/widget/widget.dart
  lib/message/message.dart
  lib/message/message_screen.dart
  lib/notification/notification.dart
  lib/notification/notification_screen.dart
  lib/pet_feed/pet_feed.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/setting/setting.dart
  lib/setting/setting_screen.dart
  pubspec.yaml
Labels: new feature

#36 Complete cached image
  lib/common/resources/resources.dart
  lib/common/resources/t_colors.dart
  lib/common/resources/t_shadows.dart
  lib/common/widgets/t_cached_image_widget.dart
  lib/common/widgets/widgets.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/module/module.dart
  petisland_core/lib/service/cache_service.dart
  petisland_core/lib/service/service.dart
  petisland_core/pubspec.yaml
  pubspec.yaml
Labels: enhancement

#38 Add constants from PetIsland's service
  petisland_core/lib/config/config.dart
  petisland_core/lib/config/constant.dart
Labels: new feature

#41 Complete Upload image
  petisland_core/assets/meow.jpeg
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/domain/comment.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/image.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/domain/review.dart
  petisland_core/lib/domain/user.dart
  petisland_core/lib/exception/exception.dart
  petisland_core/lib/exception/pesisland_exeption.dart
  petisland_core/lib/exception/petisland_api_exception.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/petisland_core.dart
  petisland_core/lib/repository/account_repository.dart
  petisland_core/lib/repository/image_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/repository/user_repository.dart
  petisland_core/lib/service/image_service.dart
  petisland_core/lib/service/service.dart
  petisland_core/test/domain_test/json_parser_test.dart
  petisland_core/test/service_test/account_test.dart
  petisland_core/test/service_test/image_test.dart
Labels: new feature

#44 Fix missing type http
  petisland_core/lib/client/http_client.dart
  petisland_core/lib/repository/account_repository.dart
Labels: new feature

#45 Post service
  petisland_core/lib/config/config.dart
  petisland_core/lib/config/constant.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/image.dart
  petisland_core/lib/domain/pet.dart
  petisland_core/lib/domain/post.dart
  petisland_core/lib/domain/post_modal.dart
  petisland_core/lib/domain/tag.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/lib/service/service.dart
  petisland_core/lib/util/log.dart
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/service_test/account_service_test.dart
  petisland_core/test/service_test/image_service_test.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: enhancement

#47 Update pet category
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/pet.dart
  petisland_core/lib/domain/pet_category.dart
  petisland_core/lib/domain/post_modal.dart
  petisland_core/test/domain_test/json_parser_test.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: new feature

#49 Pet category service
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/pet_category_repository.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/service/pet_category_service.dart
  petisland_core/lib/service/service.dart
Labels: new feature

#51 Complete remove dudate post
  petisland_core/lib/domain/post_modal.dart
Labels: enhancement

#54 Fix error create post
  petisland_core/lib/domain/post_modal.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: new feature

#55 Complete pet_category_service
  petisland_core/lib/repository/pet_category_repository.dart
  petisland_core/test/service_test/account_service_test.dart
  petisland_core/test/service_test/configuration.dart
  petisland_core/test/service_test/image_service_test.dart
  petisland_core/test/service_test/pet_category_service_test.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: new feature

#66 Tag service
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/repository.dart
  petisland_core/lib/repository/tag_repository.dart
  petisland_core/lib/service/service.dart
  petisland_core/lib/service/tag_service.dart
  petisland_core/test/service_test/post_service_test.dart
  petisland_core/test/service_test/tag_service_test.dart
Labels: service

#68 Add post like
  petisland_core/lib/repository/post_repository.dart
  petisland_core/lib/service/post_service.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: service

#71 Fix error when like post
  petisland_core/lib/repository/post_repository.dart
  petisland_core/test/service_test/post_service_test.dart
Labels: enhancement, service

#72 Complete define category
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/enum_test.dart
  petisland_core/test/utils
Labels: new feature, service

#74 Additional missing category post
  petisland_core/lib/util/petisland_constants.dart
  petisland_core/test/enum_test.dart
Labels: enhancement
