Repository 4pet-social/4pet, pull requests merged in 2020-07, with the labels that each got.

#279 Integration join and unjoin
  lib/common/resources/t_constant.dart
  lib/common/state/petisland_stateful_widget.dart
  lib/common/state/petisland_stateless_wiget.dart
  lib/common/utils/account_utils.dart
  lib/pet_feed/pet_feed_screen.dart
  lib/pet_feed/widget/post/post_image_widget.dart
  lib/pet_feed/widget/post/post_money_widget.dart
  lib/pet_feed/widget/post/post_title_widget.dart
  lib/pet_feed/widget/rescue/rescue.dart
  lib/pet_feed/widget/rescue/rescue_listing.dart
  lib/post/post_detail/screen/post_detail_screen.dart
  lib/post/post_detail/widget/comment/comment_description_widget.dart
  lib/post/post_detail/widget/post/post_detail_app_bar.dart
  lib/post/post_edit/widget/hero_title_widget.dart
  lib/post/post_edit/widget/summary_info_widget.dart
  lib/rescue_post/bloc/rescue_editing_bloc.dart
  lib/rescue_post/screen/rescue_creation_screen.dart
  lib/rescue_post/screen/rescue_detail_screen.dart
  lib/rescue_post/screen/rescue_editor_screen.dart
  lib/rescue_post/screen/screen.dart
  lib/rescue_post/widget/hero_listing_widget.dart
  lib/rescue_post/widget/preview_rescue_detail_widget.dart
  lib/rescue_post/widget/rescue_creation_detail_widget.dart
  lib/rescue_post/widget/rescue_detail_summary_widget.dart
  lib/rescue_post/widget/widget.dart
  lib/rescue_voting/screen/rescue_voting_screen.dart
  petisland_core/lib/domain/recuse.dart
  petisland_core/lib/module/dev_module_core.dart
  petisland_core/lib/repository/rescue_repository.dart
  petisland_core/lib/service/rescue_service.dart
Labels: back-end :sake:

#280 Complete integration like
  lib/main_bloc/t_worker.dart
  lib/main_bloc/t_worker_event.dart
  petisland_core/lib/repository/rescue_repository.dart
Labels: front-end :hibiscus:

#281 Add get heroes join and unjoin
  lib/pet_feed/bloc/rescue_listing_bloc.dart
  lib/rescue_post/bloc/rescue_hero_bloc.dart
  lib/rescue_post/bloc/rescue_hero_event.dart
  lib/rescue_post/screen/rescue_detail_screen.dart
  petisland_core/lib/domain/rescue_account.dart
  petisland_core/lib/repository/rescue_repository.dart
Labels: back-end :sake:

#283 Complete Integration comment
  lib/post/post_detail/bloc/comment_bloc.dart
  lib/rescue_post/bloc/rescue_comment_bloc.dart
  lib/rescue_post/screen/rescue_detail_screen.dart
  lib/rescue_post/widget/preview_rescue_detail_widget.dart
  petisland_core/lib/domain/comment.dart
  petisland_core/lib/domain/domain.dart
  petisland_core/lib/domain/rescue_comment.dart
  petisland_core/lib/repository/rescue_repository.dart
  petisland_core/lib/service/rescue_service.dart
  petisland_core/lib/utils/time.dart
Labels: front-end :hibiscus:

#284 Add edit rescue post
  lib/rescue_post/screen/rescue_detail_screen.dart
  lib/rescue_post/screen/rescue_editor_screen.dart
  petisland_core/lib/domain/recuse.dart
  petisland_core/lib/repository/rescue_repository.dart
  petisland_core/lib/service/rescue_service.dart
Labels: front-end :hibiscus:

#285 Navigate tap noti
  lib/notification/bloc/notification_bloc.dart
  lib/notification/notification.dart
  lib/notification/notification_screen.dart
  lib/notification/post_loading_screen.dart
  petisland_core/lib/repository/rescue_repository.dart
  petisland_core/lib/service/rescue_service.dart
Labels: front-end :hibiscus:

#288 Complete update logo :tada: :tada:
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/images/app_icon.png
  assets/launcher_icons/app_icon.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  script/ignore_file.sh
  script/test_driver_no_rebuild.sh
  script/test_driver_rebuild.sh
Labels: front-end :hibiscus:

#290 update: new logo
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/launcher_icons/app_icon.png
  assets/launcher_icons/slash_screen.png
  flutter_native_splash.yaml
  ios/Flutter/flutter_export_environment.sh
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
Labels: front-end :hibiscus:

#296 docs: update license
  LICENSE
Labels: document :books:

#297 Update README.md
  README.md
Labels: document :books:
